name: Run tests

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: exit 0
  test-other:
    name: Run other tests
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: exit 1
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Run unit tests
        run: sleep 10000 exit 0
