# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
    push:
        tags:
            - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
            - name: Node Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - name: Parse semver string
              id: semver_parser 
              uses: booxmedialtd/ws-action-parse-semver@v1
              with:
                input_string: ${{ github.ref_name }}
                version_extractor_regex: 'v(.*)$'
            - name: Publish Package as Public
              run: yarn publish --access=public --non-interactive
              env:
                echo "${{ github.ref_name }}""
                echo "v${{ steps.semver_parser.outputs.major }}"
                echo "v${{ steps.semver_parser.outputs.minor }}"
                echo "v${{ steps.semver_parser.outputs.patch }}"
                echo "v${{ steps.semver_parser.outputs.prerelease }}"
                echo "v${{ steps.semver_parser.outputs.build }}"
                echo "v${{ steps.semver_parser.outputs.fullversion }}"
